workflows:
  ios-unsigned-build:
    name: iOS Unsigned Build
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_CHANNEL: stable
      flutter: stable
      xcode: latest
    scripts:
      - name: Set up Flutter
        script: |
          flutter --version
          flutter pub get

      - name: Build iOS app without codesigning
        script: |
          flutter clean
          flutter build ios --release --no-codesign

      - name: Create unsigned .ipa
        script: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r Runner.ipa Payload
          mv Runner.ipa $CM_BUILD_DIR
          rm -rf Payload

    artifacts:
      - Runner.ipa

    publishing:
      email:
        recipients:
          - shivamingulkar17@gmail.com  # <-- Change this if needed
