workflows:
  ios-unsigned-native:
    name: iOS Unsigned Native Build
    max_build_duration: 60
    environment:
      xcode: latest  # Make sure Codemagic is using the latest Xcode version
    scripts:
      # Step 1: Build iOS app without code signing
      - name: Build iOS app (no code signing)
        script: |
          xcodebuild \
            -workspace project.xcworkspace \
            -scheme Clear \
            -configuration Release \
            -sdk iphoneos \
            -destination generic/platform=iOS \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            build

      # Step 2: Export unsigned IPA
      - name: Export .ipa
        script: |
          mkdir -p build/Release-iphoneos/Payload
          cp -r build/Release-iphoneos/Clear.app build/Release-iphoneos/Payload/
          cd build/Release-iphoneos
          zip -r Clear.ipa Payload
          mv Clear.ipa $CM_BUILD_DIR

    artifacts:
      - build/Release-iphoneos/Clear.ipa

    publishing:
      email:
        recipients:
          - shivamingulkar17@gmail.com
