workflows:
  ios-unsigned-native:
    name: iOS Unsigned Native Build
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Install XcodeGen
        script: brew install xcodegen

      - name: Generate Xcode project
        script: xcodegen

      - name: Build iOS app (no code signing)
        script: |
          xcodebuild \
            -project Clear.xcodeproj \
            -scheme Clear \
            -sdk iphoneos \
            -configuration Release \
            -destination generic/platform=iOS \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            build

      - name: Export .ipa
        script: |
          mkdir -p build/Release-iphoneos/Payload
          cp -r build/Release-iphoneos/Clear.app build/Release-iphoneos/Payload/
          cd build/Release-iphoneos
          zip -r Clear.ipa Payload
          mv Clear.ipa $CM_BUILD_DIR

    artifacts:
      - build/Release-iphoneos/Clear.ipa

    publishing:
      email:
        recipients:
          - shivamingulkar17@gmail.com
