workflows:
  ios-unsigned:
    name: iOS Unsigned IPA Build
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Build iOS app (no code signing)
        script: |
          xcodebuild \
            -project project.xcodeproj \
            -scheme Clear \
            -sdk iphoneos \
            -configuration Release \
            -destination generic/platform=iOS \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            build

      - name: Package .ipa
        script: |
          mkdir -p Payload
          cp -r build/Release-iphoneos/Clear.app Payload/
          zip -r Clear.ipa Payload
          mv Clear.ipa $CM_BUILD_DIR

    artifacts:
      - Clear.ipa

    publishing:
      email:
        recipients:
          - shivamingulkar17@gmail.com
