workflows:
  ios-unsigned-native:
    name: IOS Unsigned Native Build
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Install XcodeGen
        script: brew install xcodegen

      - name: Generate Xcode project
        script: xcodegen

      - name: Build iOS app (no code signing)
        script: |
          xcodebuild \
            -project Clear.xcodeproj \
            -scheme Clear \
            -sdk iphoneos \
            -configuration Release \
            -destination generic/platform=iOS \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            build

      - name: Export .ipa (Fixed path)
        script: |
          echo "🔍 Searching for .app..."
          APP_PATH=$(find . -type d -name "Clear.app" | head -n 1)

          if [ -z "$APP_PATH" ]; then
            echo "❌ Clear.app not found!"
            exit 1
          fi

          echo "✅ Found app at: $APP_PATH"

          mkdir -p Payload
          cp -r "$APP_PATH" Payload/
          zip -r Clear.ipa Payload
          mv Clear.ipa $CM_BUILD_DIR

    artifacts:
      - Clear.ipa

    publishing:
      email:
        recipients:
          - shivamingulkar17@gmail.com
