workflows:
  ios:
    name: Build iOS App Without Signing
    platform: ios
    version: stable
    sdk: iphoneos
    script:
      # Any custom script (if needed) can be added here
      - echo "Skipping signing process"
    build:
      ios:
        xcode: "14.0"  # Ensure this matches the Xcode version your app needs
        scheme: "Clear"
        configuration: "Release"
        archive: true
        export_method: "development"  # Use "development" method for unsigned builds
        export_options:
          signingStyle: "none"  # Completely skip signing
    artifacts:
      - build/ios/ipa/*.ipa  # The location of the generated IPA
