workflows:
  ios-unsigned-build:
    name: Clear iOS Unsigned Build
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          brew install cocoapods
          pod install
      - name: Build unsigned .ipa
        script: |
          xcodebuild -workspace Clear.xcworkspace \
                     -scheme Clear \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $HOME/Library/Developer/Xcode/Archives/Clear.xcarchive \
                     archive
          xcodebuild -exportArchive \
                     -archivePath $HOME/Library/Developer/Xcode/Archives/Clear.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath $CM_BUILD_DIR/build
    artifacts:
      - build/*.ipa