name: Clear
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 13.0
targets:
  Clear:
    type: application
    platform: iOS
    sources: [ . ]
    info: Info.plist
    dependencies: []
    settings:
      base:
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO