name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4  # Corrected checkout version to v4

    - name: Set up Xcode
      uses: apple-actions/setup-xcode@v2  # Correct action for setting up Xcode
      with:
        xcode-version: '14.0'  # Specify the version of Xcode that suits your project

    - name: Install XcodeGen
      run: |
        brew install xcodegen  # Ensure XcodeGen is installed to generate the Xcode project

    - name: Generate Xcode project using XcodeGen
      run: |
        xcodegen generate  # Generates the Xcode project from the xcodegen.yml file

    - name: Build iOS app
      run: |
        xcodebuild -scheme "Clear" -workspace "Clear.xcworkspace" -destination "platform=iOS" clean build

    - name: Upload IPA file as artifact
      uses: actions/upload-artifact@v4  # Upload the resulting IPA file as an artifact
      with:
        name: Clear-build-ipa
        path: build/Release-iphoneos/Clear.ipa  # Adjust this path if necessary
