name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: apple-actions/setup-xcode@v2
      with:
        xcode-version: '13.2' # Make sure the version matches your requirements

    - name: Install Dependencies (CocoaPods or other)
      run: |
        gem install cocoapods
        pod install

    - name: Generate Xcode project using XcodeGen
      run: |
        xcodegen generate

    - name: Build iOS app
      run: |
        xcodebuild -scheme "YourScheme" -workspace "YourWorkspace.xcworkspace" -destination "platform=iOS" clean build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-ipa
        path: path/to/your/output.ipa
