name: Generate Xcode Project with XcodeGen

on:
  push:
    branches:
      - main

jobs:
  generate-xcode-project:
    runs-on: macos-latest  # Run on a macOS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install XcodeGen
        run: |
          brew install xcodegen  # Install XcodeGen on the macOS runner

      - name: Generate Xcode project
        run: |
          xcodegen generate  # Run XcodeGen to generate the .xcodeproj file
      
      - name: Commit generated Xcode project
        run: |
          git add .
          git commit -m "Generate Xcode project"
          git push
